# config/packages/security.yaml
security:
    # ...
    providers:
        user_db:
            entity: { class: App\Entity\User, property: email }
    encoders:
        # use your user class name here
        App\Entity\User:
            # Use native password encoder
            # This value auto-selects the best possible hashing algorithm
            # (i.e. Sodium when available).
            algorithm: auto

    firewalls:
        main:
            anonymous: true
            lazy: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   app_logout
        secured_area:
            # ...
            form_login:
                # ...
                csrf_token_generator: security.csrf.token_manager
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CANDIDATE,ROLE_EMPLOYER]
